## Python ile veri analizi


In [2]:
# NumPy
# pandas
# Veri Görselleştirme: Matplotlib ve Seaborn
#Gelişmiş Fonksiyonel Keşifçi Veri Analizi(Advanced Functional Exploratory Data Analysis)

Neden NumPy?

NumPy Array'i oluşturmak

NumPy Array Özellikleri

Yeniden Şekillendirme

Index Seçimi

Slicing

Fancy Index

Numpy'da Koşullu İşlemler

Matematiksel İşlemler

In [3]:
import numpy as np

In [4]:
a =[ 1,2,3,4,]

In [5]:
b=[ 1,2,3,4,]

In [6]:
ab=[]

In [8]:
for i in range(0, len(a)):
    ab.append(a[i] * b[i])

In [9]:
ab

[1, 4, 9, 16]

In [10]:
a= np.array([1,2,3,4])
b= np.array([1,2,3,4])
a*b

array([ 1,  4,  9, 16])

In [11]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [12]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [13]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.random.randint(0,10, size=10)

array([0, 9, 0, 8, 4, 8, 8, 8, 5, 4])

In [16]:
np.random.normal(10,4,(3,4))

array([[ 8.77593149, 11.98007212,  4.60525074,  9.77274418],
       [ 8.63561832, 10.08845336, 15.01353861, 14.31203315],
       [10.00567639, 17.09043365,  8.57937382, 20.06106271]])

In [17]:
# ndim: boyut sayısı
# shape: boyut bilgisi
# size: toplam eleman sayısı
#dtype: array veri tipi

In [7]:
a= np.random.randint(10, size=5)

In [8]:
a.ndim

1

In [9]:
a.shape

(5,)

In [10]:
a.size

5

In [11]:
a.dtype

dtype('int64')

In [12]:
a= np.random.randint(10, size=9)

In [13]:
a

array([6, 1, 7, 7, 4, 6, 7, 0, 5])

In [14]:
a= np.random.randint(10, size=9).reshape(3,3)

In [15]:
a

array([[3, 1, 8],
       [5, 1, 1],
       [7, 6, 6]])

In [16]:
a= np.random.randint(10, size=10)

In [17]:
a

array([6, 6, 0, 8, 9, 1, 4, 7, 4, 1])

In [18]:
a[0]

6

In [19]:
a[0:5]

array([6, 6, 0, 8, 9])

In [20]:
a[0]=999

In [24]:
m=np.random.randint(10, size=(3,5)) # 0'dan 10'a kadar sayılardan olsun, 3 satırlı 5 sutunlu array

In [25]:
m

array([[1, 9, 9, 9, 9],
       [9, 3, 5, 1, 2],
       [5, 2, 6, 9, 3]])

In [26]:
m[0,0]  # satır.sütun

1

In [36]:
m[1,1]

4

In [37]:
m[2,3]=999

In [38]:
m

array([[  6,   9,   2,   4,   7],
       [  3,   4,   6,   2,   1],
       [  4,   4,   8, 999,   8]])

In [39]:
m[2,3]=2.9

In [40]:
m

array([[6, 9, 2, 4, 7],
       [3, 4, 6, 2, 1],
       [4, 4, 8, 2, 8]])

In [41]:
m[:,0] #bütün satırları seç 0.sütunu seç

array([6, 3, 4])

In [42]:
m[1,:]# 1.satır tüm sutunlar

array([3, 4, 6, 2, 1])

In [43]:
m[0:2,0:3]

array([[6, 9, 2],
       [3, 4, 6]])

In [27]:
## Fancy Index

In [28]:
import numpy as np

In [30]:
v= np.arange(0,30,3) #0'dan 30'a kakdar üçer üçer artacak şekilde array oluştur.

In [31]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [32]:
catch=[1,2,3]

In [33]:
v[catch]

array([3, 6, 9])

In [35]:
n=np.array([1,2,3,4,5])

In [36]:
#klasik python döngüler kullanarak

In [37]:
ab=[]

In [38]:
for i in n:
    print(i)

1
2
3
4
5


In [39]:
for i in n:
    if i<3:
        ab.append(i)

In [40]:
ab

[1, 2]

In [41]:
#Numpy ile

In [42]:
n<3

array([ True,  True, False, False, False])

In [43]:
n[n<3]

array([1, 2])

In [44]:
n[n<3]
n[n>3]
n[n !=3]
n[n==3]
n[n>=3]

array([3, 4, 5])

In [45]:
n*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [46]:
# NumPy ile İki Bİlinmeyenli Denklem Çözümü

In [47]:
# 5 + x0 + x1=12
# x0 + 3x1=10

In [48]:
a= np.array([[5,1], [1,3]])
b=np.array([12,10])

In [49]:
np.linalg.solve(a,b)

array([1.85714286, 2.71428571])

In [52]:
arr= np.array([[1,2,3,4,5,],[6,7,8,9,10]])

In [53]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [54]:
arr[0,1]

2

In [55]:
ar=np.array([1,2,3,4,5,6,7])

In [56]:
print(ar[-3:-1])

[5 6]


In [57]:
ar

array([1, 2, 3, 4, 5, 6, 7])

In [58]:
#Verilen kodda arr[-3:-1] ifadesi kullanılıyor. NumPy dizilerinde negatif indeksler, dizinin sonundan başlamaktadır. Yani:

#-1 son elemanı (6) gösterir.
#-2 sondan bir önceki elemanı (5) gösterir.
#-3 sondan iki önceki elemanı (4) gösterir.
#Dolayısıyla, arr[-3:-1] ifadesi 4 ve 5 elemanlarını içerir, ancak -1 indeksi dahil edilmediği için sonuç olarak sadece 4 ve 5 elemanlarını alır.

## Pandas

In [1]:
# Pandas Series
# Veri Okuma (Reading Data)
#Veriye HızLı Bakış
# Pandas'ta Seçim İşlemleri
#Toplulaştırma ve Gruplama
# Apply ve Lambda
#Birleştirme İşlemleri


In [2]:
import pandas as pd

In [4]:
s= pd.Series([10,72,12,4,5]) #metot

In [5]:
type(s)

pandas.core.series.Series

In [6]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [7]:
s.dtype

dtype('int64')

In [8]:
s.size

5

In [9]:
s.ndim #boyut bilgisi


1

In [10]:
s.values


array([10, 72, 12,  4,  5])

In [11]:
type(s.values) #numpy verdi

numpy.ndarray

In [13]:
s.head(3)

0    10
1    72
2    12
dtype: int64

In [14]:
s.tail(3)

2    12
3     4
4     5
dtype: int64

### Veri Okuma

In [22]:
import pandas as pd

In [23]:
df=pd.read_csv("Desktop/JupyterLab_Notebook_Temelleri/Veri_Analizi.ipynb")

FileNotFoundError: [Errno 2] No such file or directory: 'Desktop/JupyterLab_Notebook_Temelleri/Veri_Analizi.ipynb'

In [24]:
import pandas as pd

In [25]:
import seaborn as sns

In [27]:
df=sns.load_dataset("titanic")

In [28]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [29]:
df.tail() #sondan değerlere göz atma

survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second   
887         1       1  female  19.0      0      0  30.00        S   First   
888         0       3  female   NaN      1      2  23.45        S   Third   
889         1       1    male  26.0      0      0  30.00        C   First   
890         0       3    male  32.0      0      0   7.75        Q   Third   

       who  adult_male deck  embark_town alive  alone  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True

In [31]:
df.shape #boyut bilgisi

(891, 15)

In [32]:
df.info() #genel özet bilgi veriyor

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [33]:
df.columns #değişken isimleri

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [34]:
df.index # dataframe'in index bilgileri

RangeIndex(start=0, stop=891, step=1)

In [35]:
df.describe().T

count       mean        std   min      25%      50%   75%       max
survived  891.0   0.383838   0.486592  0.00   0.0000   0.0000   1.0    1.0000
pclass    891.0   2.308642   0.836071  1.00   2.0000   3.0000   3.0    3.0000
age       714.0  29.699118  14.526497  0.42  20.1250  28.0000  38.0   80.0000
sibsp     891.0   0.523008   1.102743  0.00   0.0000   0.0000   1.0    8.0000
parch     891.0   0.381594   0.806057  0.00   0.0000   0.0000   0.0    6.0000
fare      891.0  32.204208  49.693429  0.00   7.9104  14.4542  31.0  512.3292

In [36]:
df.isnull().values.any()

True

In [37]:
#values ifadesi dönünce numpy dönüyor

In [38]:
df.isnull().sum # veri setinde değişkenlerdeki eksiklik durumu


<bound method NDFrame._add_numeric_operations.<locals>.sum of      survived  pclass    sex    age  sibsp  parch   fare  embarked  class  \
0       False   False  False  False  False  False  False     False  False   
1       False   False  False  False  False  False  False     False  False   
2       False   False  False  False  False  False  False     False  False   
3       False   False  False  False  False  False  False     False  False   
4       False   False  False  False  False  False  False     False  False   
..        ...     ...    ...    ...    ...    ...    ...       ...    ...   
886     False   False  False  False  False  False  False     False  False   
887     False   False  False  False  False  False  False     False  False   
888     False   False  False   True  False  False  False     False  False   
889     False   False  False  False  False  False  False     False  False   
890     False   False  False  False  False  False  False     False  False   

       who  a

In [39]:
df["sex"].head()

0      male
1    female
2    female
3    female
4      male
Name: sex, dtype: object

In [40]:
df["sex"].value_counts()

male      577
female    314
Name: sex, dtype: int64